json.id reservation.id
json.user_id reservation.user_id
json.room_id reservation.room_id
json.start_date reservation.start_date
json.end_date reservation.end_date
json.price reservation.price
json.total reservation.total
json.created_at reservation.created_at
json.updated_at reservation.updated_at